---
title: "Predict sequences"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{predict}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


Deepredeff package allows you to predict effector protein given amino acid sequences in different format. Format that can be used for this version are fasta, dataframe, AAString, and AAStringSet. 

How do you predict your sequences using deepredeff? In this article, we will walk you through the steps. The function to predict is `predict_effector`. There are four model available in this version, which are bacteria, fungi, oomycete, and all. Each model is specifically trained using different class of training data.

To use code in this article, you will need to install the following packages: `reticulate`, `dplyr`, and `deepredeff`. Before running the function, it is necessary to set up the conda environment that you will use. 

```r
reticulate::use_condaenv("tensorflow", conda = "/usr/local/Caskroom/miniconda/base/bin/conda")
library(dplyr)
library(deepredeff)
```

## Predict

In this article, some examples using different input format will be shown. 

### FASTA format 

The fasta example that will be used is the example fungi sequences in this package. We can define the input as follows.

```r
input_fasta_path <- system.file("extdata/example/fungi_sample.fasta", package = "deepredeff")
```


```r
pred_fungi_input_fasta <- deepredeff::predict_effector(
  input = input_fasta_path,
  model = "fungi"
)
#> Loaded models: cnn_lstm for pathogen fungi.
#> Loaded models successfully!
```


``` r
pred_fungi_input_fasta %>% 
  dplyr::select(c(name, prob))
#>                              name        prob
#> 1  tr|A0A0A0S3X0|A0A0A0S3X0_LEPMC 0.949224353
#> 2  tr|A0A0A2ILW0|A0A0A2ILW0_PENEN 0.976694226
#> 3  tr|A0A0A2JB06|A0A0A2JB06_PENEN 0.980522037
#> 4  tr|A0A0A2JVC2|A0A0A2JVC2_PENEN 0.954952955
#> 5  tr|A0A0A2JY92|A0A0A2JY92_PENEN 0.981008828
#> 6          tr|F9XPG6|F9XPG6_ZYMTI 0.087577999
#> 7          tr|G2XB99|G2XB99_VERDV 0.038996011
#> 8          tr|G2WR20|G2WR20_VERDV 0.022782654
#> 9          tr|G2X460|G2X460_VERDV 0.004808956
#> 10 tr|A0A0D1C4R8|A0A0D1C4R8_USTMA 0.106814429
```


### Data frame format 

Using the fasta of oomycete data in this `deepredeff` pakcage, we can then transform the path to dataframe. We can use the function `fasta_to_df` from this package. We can define the input as follows

```r
input_dataframe <- system.file("extdata/example/oomycete_sample.fasta", package = "deepredeff") %>%
      deepredeff::fasta_to_df() 
```


```r
pred_oomycete_input_df <- deepredeff::predict_effector(
  input = input_dataframe,
  model = "oomycete"
)
#> Loaded models: cnn_lstm for pathogen oomycete.
#> Loaded models successfully!
```

```r
pred_oomycete_input_df %>% 
  dplyr::select(c(name, prob))
#>                         name      prob
#> 1  sp|A0A0M5K865|CR108_PHYSO 0.3380925
#> 2     tr|A5YTY8|A5YTY8_PHYSO 0.7775228
#> 3     tr|A7L812|A7L812_PHYSO 0.4298682
#> 4     tr|B2C6F8|B2C6F8_9STRA 0.6125270
#> 5     tr|C0LF23|C0LF23_PHYSO 0.5669487
#> 6     tr|G4Z8J9|G4Z8J9_PHYSP 0.3983551
#> 7     tr|G4ZVW1|G4ZVW1_PHYSP 0.4206038
#> 8     tr|G4Z8A0|G4Z8A0_PHYSP 0.4387988
#> 9     tr|G5A7C4|G5A7C4_PHYSP 0.2261022
#> 10    tr|G4ZGN2|G4ZGN2_PHYSP 0.2656690
```



### AAStringSet format

Using one of function from Biostrings, we can transform the example bacteria fasta we provide in this package to AAstringSet class data. We can define the input as follows

```r
input_aastringset <- system.file("extdata/example/bacteria_sample.fasta", package = "deepredeff") %>%
      Biostrings::readAAStringSet()
```


```r
pred_bacteria_input_aastringset <- deepredeff::predict_effector(
  input = input_aastringset,
  model = "bacteria"
)
#> Loaded models: cnn_gru, cnn_lstm, gru_emb, lstm_emb for pathogen bacteria.
#> Loaded models successfully!
```

```r
pred_bacteria_input_aastringset %>% 
  dplyr::select(c(name, prob))
  
#>                                                                                                                                                                                 name
#> 1                                      tr|A0A0N8SZV2|A0A0N8SZV2_PSESY Type III secretion system effector HopAI1 OS=Pseudomonas syringae pv. syringae OX=321 GN=ALO45_04155 PE=4 SV=1
#> 2                                             tr|A5CLR7|A5CLR7_CLAM3 Pat-1 protein OS=Clavibacter michiganensis subsp. michiganensis (strain NCPPB 382) OX=443906 GN=pat-1 PE=4 SV=1
#> 3                                                   sp|B2SU53|PTHX1_XANOP TAL effector protein PthXo1 OS=Xanthomonas oryzae pv. oryzae (strain PXO99A) OX=360094 GN=pthXo1 PE=1 SV=2
#> 4                                                                       tr|C0SPN9|C0SPN9_RALSL Uncharacterized protein RSc2139 OS=Ralstonia solanacearum OX=305 GN=RSc2139 PE=4 SV=1
#> 5                                                                               tr|D2Z000|D2Z000_RALSL Type III effector protein OS=Ralstonia solanacearum OX=305 GN=rip61 PE=4 SV=1
#> 6                       tr|Q8XX20|Q8XX20_RALSO Putative multicopper oxidase, type 3 signal peptide protein OS=Ralstonia solanacearum (strain GMI1000) OX=267608 GN=RSc2298 PE=4 SV=1
#> 7  tr|Q87UH8|Q87UH8_PSESM Taurine ABC transporter, periplasmic taurine-binding protein OS=Pseudomonas syringae pv. tomato (strain ATCC BAA-871 / DC3000) OX=223283 GN=tauA PE=4 SV=1
#> 8      tr|Q4ZTI0|Q4ZTI0_PSEU2 Amino acid ABC transporter substrate-binding protein, PAAT family OS=Pseudomonas syringae pv. syringae (strain B728a) OX=205918 GN=Psyr_2503 PE=4 SV=1
#> 9                                                         tr|Q4ZR15|Q4ZR15_PSEU2 Sensor protein OS=Pseudomonas syringae pv. syringae (strain B728a) OX=205918 GN=Psyr_3375 PE=4 SV=1
#> 10                                                         tr|D4I1R4|D4I1R4_ERWAC Outer-membrane lipoprotein LolB OS=Erwinia amylovora (strain CFBP1430) OX=665029 GN=lolB PE=3 SV=1
#>          prob
#> 1  0.94834238
#> 2  0.07981773
#> 3  0.99433608
#> 4  0.84184440
#> 5  0.99537852
#> 6  0.06455157
#> 7  0.04928583
#> 8  0.30616181
#> 9  0.07221440
#> 10 0.04899144
```

### AAString format

Similar to how we define AAStringSet, we can also use one of function from Biostrings to transform a string to AAstring class data.

```r
input_aastring <- system.file("extdata/example/bacteria_sample.fasta", package = "deepredeff") %>%
      fasta_to_df() %>%
      dplyr::slice(1) %>%
      dplyr::pull(sequence) %>%
      Biostrings::AAString()
```


```r
pred_bacteria_input_aastring <- deepredeff::predict_effector(
  input = input_aastring,
  model = "bacteria"
)
#> Loaded models: cnn_gru, cnn_lstm, gru_emb, lstm_emb for pathogen bacteria.
#> Loaded models successfully!
```

```r
pred_bacteria_input_aastring  %>% 
  dplyr::select(c(name, prob))
#>                                                                                                                                                                                                                                                                          name
#> 1 MPINRPAFNLKLNTAIAQPTLKKDAGAELRRLNQSEVRANTQTRFAVNHRAPTYDVAQSALGENHGGWTAANHFKMTGSEVFIHMDRLEPNCKGEFAGDKIHLSVAPEDVPDAFNAIGKILQASDSPVDSWKVTDMKCLQAEMPAAKQRVALGAQFTIYAKPDREDNTYSPEYMGKMRGMISSIEQELSAAGVRQSSHRPDSDVSPGHWSYASYRNEHKSNRSGTSNQHRNLEAEPFFQLVSFSDGASGSSRSSADHQALLPPPWAR
#>        prob
#> 1 0.9483424
```



## Summarise and plot

Using the results you obtained as presented above, you can then take a look on the summary of the prediction. As well as plot them. In this section, we will show you how to do that. Let us take the frist prediction result using fasta as the input data. If you want to take a look on the summary of your prediction, you can do this following step: 

```r
summary(pred_fungi_input_fasta)
#> # A tibble: 2 x 3
#>   pred_class count ratio
#>        <dbl> <int> <dbl>
#> 1          0     5   0.5
#> 2          1     5   0.5
```

```r
summary(pred_oomycete_input_df)
#> # A tibble: 2 x 3
#>   pred_class count ratio
#>        <dbl> <int> <dbl>
#> 1          0     7   0.7
#> 2          1     3   0.3
```


